# Generated by Django 4.2.5 on 2023-10-04 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringIntervalModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.basemodel')),
                ('choice', models.CharField(choices=[('every_month', 'Каждый месяц'), ('every_week', 'Каждую неделю'), ('every_day', 'Каждый день'), ('every_hour', 'Каждый час')], default=('every_month', 'Каждый месяц'), max_length=255, verbose_name='Интервал транзакции')),
            ],
            bases=('catalogs.basemodel',),
        ),
    ]
