# Generated by Django 4.2.5 on 2023-10-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringintervalmodel',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='RecurringIntervalModel',
        ),
    ]
