# Generated by Django 4.2.5 on 2023-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.TextField(blank=True, default='/static/images/anonymous_user.png', null=True),
        ),
    ]
