# Generated by Django 4.2.5 on 2023-10-05 12:36

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_firstname_user_lastname_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=djstripe.fields.StripeIdField(max_length=500, null=True),
        ),
    ]
