# Generated by Django 4.2.5 on 2023-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_user',
            field=models.BooleanField(default=False, editable=False, verbose_name='This field need inform that user has created in stripe service'),
        ),
    ]
